-- 第二阶段：PostgreSQL 建表脚本
-- 基于第一阶段/02-数据字典.csv 与 03-实体关系分析.md
-- PostgreSQL 14+
BEGIN;
CREATE SCHEMA IF NOT EXISTS patentdb;
SET search_path TO patentdb, public;

CREATE TABLE patentdb.dataset (
    dataset_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dataset_code VARCHAR(20) NOT NULL,
    dataset_name_cn VARCHAR(200) NOT NULL,
    dataset_name_en VARCHAR(200),
    office_code CHAR(2) NOT NULL,
    data_category VARCHAR(20) NOT NULL,
    file_format VARCHAR(20) NOT NULL,
    manual_ref VARCHAR(500),
    description TEXT,
    CONSTRAINT pk_dataset PRIMARY KEY (dataset_id),
    CONSTRAINT uq_dataset_dataset_code UNIQUE (dataset_code)
);

CREATE TABLE patentdb.country_office (
    ctry_code CHAR(2) NOT NULL,
    iso_alpha3 CHAR(3),
    st3_name VARCHAR(100) NOT NULL,
    name_cn VARCHAR(100),
    organisation_flag CHAR(1) NOT NULL,
    continent VARCHAR(25),
    is_epo_member CHAR(1) NOT NULL,
    is_eu_member CHAR(1) NOT NULL,
    discontinued CHAR(1) NOT NULL,
    CONSTRAINT pk_country_office PRIMARY KEY (ctry_code),
    CONSTRAINT uq_country_office_iso_alpha3 UNIQUE (iso_alpha3)
);

CREATE TABLE patentdb.language (
    lang_code CHAR(2) NOT NULL,
    name_en VARCHAR(50) NOT NULL,
    name_cn VARCHAR(50),
    CONSTRAINT pk_language PRIMARY KEY (lang_code)
);

CREATE TABLE patentdb.kind_code (
    office_code CHAR(2) NOT NULL,
    kind_code VARCHAR(2) NOT NULL,
    kind_description_en VARCHAR(200) NOT NULL,
    kind_description_cn VARCHAR(200) NOT NULL,
    publication_level CHAR(1),
    is_grant CHAR(1) NOT NULL,
    note VARCHAR(200),
    CONSTRAINT pk_kind_code PRIMARY KEY (office_code, kind_code)
);

CREATE TABLE patentdb.application_type (
    appl_type_code VARCHAR(20) NOT NULL,
    appl_type_name_en VARCHAR(100) NOT NULL,
    appl_type_name_cn VARCHAR(100) NOT NULL,
    ipr_type CHAR(2),
    CONSTRAINT pk_application_type PRIMARY KEY (appl_type_code)
);

CREATE TABLE patentdb.classification_scheme (
    scheme_code VARCHAR(10) NOT NULL,
    scheme_name_en VARCHAR(100) NOT NULL,
    scheme_name_cn VARCHAR(100) NOT NULL,
    authority CHAR(2),
    symbol_format VARCHAR(100),
    is_hierarchical CHAR(1) NOT NULL,
    CONSTRAINT pk_classification_scheme PRIMARY KEY (scheme_code)
);

CREATE TABLE patentdb.legal_event_code (
    event_auth CHAR(2) NOT NULL,
    event_code VARCHAR(4) NOT NULL,
    event_impact CHAR(1),
    event_descr VARCHAR(250) NOT NULL,
    event_descr_orig VARCHAR(250),
    event_category_code CHAR(1),
    event_category_title VARCHAR(100),
    CONSTRAINT pk_legal_event_code PRIMARY KEY (event_auth, event_code)
);

CREATE TABLE patentdb.citation_category (
    category_code VARCHAR(10) NOT NULL,
    category_desc_en VARCHAR(200) NOT NULL,
    category_desc_cn VARCHAR(200) NOT NULL,
    source_standard VARCHAR(30) NOT NULL,
    note VARCHAR(200),
    CONSTRAINT pk_citation_category PRIMARY KEY (category_code)
);

CREATE TABLE patentdb.keyword (
    keyword_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    keyword_text VARCHAR(200) NOT NULL,
    lang_code CHAR(2) NOT NULL,
    source VARCHAR(50),
    CONSTRAINT pk_keyword PRIMARY KEY (keyword_id),
    CONSTRAINT uq_keyword_keyword_text_lang_code UNIQUE (keyword_text, lang_code)
);

CREATE TABLE patentdb.ipc_techn_field (
    ipc_maingroup_symbol VARCHAR(8) NOT NULL,
    techn_field_nr SMALLINT NOT NULL,
    techn_sector VARCHAR(50),
    techn_field VARCHAR(50),
    CONSTRAINT pk_ipc_techn_field PRIMARY KEY (ipc_maingroup_symbol)
);

CREATE TABLE patentdb.patent (
    patent_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dataset_id BIGINT NOT NULL,
    appln_auth CHAR(2) NOT NULL,
    appln_nr VARCHAR(30) NOT NULL,
    appln_kind VARCHAR(2) NOT NULL,
    appln_nr_original VARCHAR(100),
    appln_nr_epodoc VARCHAR(30),
    appl_type_code VARCHAR(20),
    appln_filing_date DATE NOT NULL,
    appln_filing_date_raw CHAR(8),
    receiving_office CHAR(2),
    appln_lang CHAR(2),
    int_phase CHAR(1) NOT NULL,
    reg_phase CHAR(1) NOT NULL,
    nat_phase CHAR(1) NOT NULL,
    rights_effective_date DATE,
    us_application_series_code VARCHAR(5),
    botanic_latin_name VARCHAR(200),
    botanic_variety VARCHAR(200),
    CONSTRAINT pk_patent PRIMARY KEY (patent_id),
    CONSTRAINT uq_patent_appln_business_key UNIQUE (appln_auth,appln_nr,appln_kind)
);

CREATE TABLE patentdb.publication (
    publication_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patent_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    publn_auth CHAR(2) NOT NULL,
    publn_nr VARCHAR(30) NOT NULL,
    publn_kind VARCHAR(2) NOT NULL,
    publn_date DATE,
    publn_date_raw CHAR(8),
    publn_lg CHAR(2),
    publn_first_grant CHAR(1) NOT NULL,
    term_length_years SMALLINT,
    term_extension_days INT,
    number_of_claims INT,
    number_of_figures INT,
    number_of_drawing_sheets INT,
    gazette_number VARCHAR(20),
    docdb_doc_id VARCHAR(20),
    date_added_docdb DATE,
    CONSTRAINT pk_publication PRIMARY KEY (publication_id),
    CONSTRAINT uq_publication_doc_key UNIQUE (publn_auth,publn_nr,publn_kind)
);

CREATE TABLE patentdb.title (
    title_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    publication_id BIGINT NOT NULL,
    lang_code CHAR(2) NOT NULL,
    title_text VARCHAR(2000) NOT NULL,
    title_type VARCHAR(10) NOT NULL,
    is_original CHAR(1),
    data_format VARCHAR(20),
    CONSTRAINT pk_title PRIMARY KEY (title_id),
    CONSTRAINT uq_title_pub_lang_type UNIQUE (publication_id,lang_code,title_type)
);

CREATE TABLE patentdb.abstract (
    abstract_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    publication_id BIGINT NOT NULL,
    lang_code CHAR(2) NOT NULL,
    abstract_text TEXT NOT NULL,
    data_format VARCHAR(20),
    abstract_source VARCHAR(50),
    CONSTRAINT pk_abstract PRIMARY KEY (abstract_id),
    CONSTRAINT uq_abstract_pub_lang UNIQUE (publication_id,lang_code)
);

CREATE TABLE patentdb.description_section (
    section_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    publication_id BIGINT NOT NULL,
    parent_section_id BIGINT,
    section_seq INT NOT NULL,
    section_level SMALLINT,
    heading VARCHAR(500),
    section_text TEXT,
    CONSTRAINT pk_description_section PRIMARY KEY (section_id),
    CONSTRAINT uq_description_pub_seq UNIQUE (publication_id,section_seq)
);

CREATE TABLE patentdb.drawing (
    drawing_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    publication_id BIGINT NOT NULL,
    figure_seq INT NOT NULL,
    figure_id VARCHAR(64),
    image_file VARCHAR(255),
    alt_text VARCHAR(200),
    CONSTRAINT pk_drawing PRIMARY KEY (drawing_id),
    CONSTRAINT uq_drawing_pub_seq UNIQUE (publication_id,figure_seq)
);

CREATE TABLE patentdb.claim (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    publication_id BIGINT NOT NULL,
    lang_code CHAR(2) NOT NULL,
    claim_number INT NOT NULL,
    claim_seq INT NOT NULL,
    claim_type CHAR(1) NOT NULL,
    claim_text TEXT NOT NULL,
    xml_claim_id VARCHAR(64),
    CONSTRAINT pk_claim PRIMARY KEY (claim_id),
    CONSTRAINT uq_claim_pub_lang_no UNIQUE (publication_id,lang_code,claim_number)
);

CREATE TABLE patentdb.claim_dependency (
    dependent_claim_id BIGINT NOT NULL,
    parent_claim_id BIGINT NOT NULL,
    dependency_type VARCHAR(20),
    ref_text VARCHAR(200),
    CONSTRAINT pk_claim_dependency PRIMARY KEY (dependent_claim_id, parent_claim_id)
);

CREATE TABLE patentdb.person (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_name VARCHAR(500) NOT NULL,
    person_name_orig VARCHAR(500),
    person_type CHAR(1) NOT NULL,
    address_text VARCHAR(1000),
    city VARCHAR(200),
    state_province VARCHAR(100),
    postcode VARCHAR(30),
    ctry_code CHAR(2),
    residence_ctry_code CHAR(2),
    doc_std_name VARCHAR(500),
    psn_id INT,
    epo_person_id VARCHAR(20),
    source_dataset_id BIGINT,
    CONSTRAINT pk_person PRIMARY KEY (person_id)
);

CREATE TABLE patentdb.natural_person (
    person_id BIGINT NOT NULL,
    last_name VARCHAR(200),
    first_name VARCHAR(200),
    middle_name VARCHAR(200),
    CONSTRAINT pk_natural_person PRIMARY KEY (person_id)
);

CREATE TABLE patentdb.organization (
    person_id BIGINT NOT NULL,
    org_name VARCHAR(500) NOT NULL,
    psn_sector VARCHAR(50),
    CONSTRAINT pk_organization PRIMARY KEY (person_id)
);

CREATE TABLE patentdb.patent_applicant (
    patent_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    sequence_nr SMALLINT NOT NULL,
    applicant_type VARCHAR(20),
    authority_category VARCHAR(50),
    designation VARCHAR(50),
    internal_ref VARCHAR(100),
    CONSTRAINT pk_patent_applicant PRIMARY KEY (patent_id, sequence_nr)
);

CREATE TABLE patentdb.patent_inventor (
    patent_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    sequence_nr SMALLINT NOT NULL,
    designation VARCHAR(50),
    internal_ref VARCHAR(100),
    CONSTRAINT pk_patent_inventor PRIMARY KEY (patent_id, sequence_nr)
);

CREATE TABLE patentdb.patent_assignee (
    patent_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    sequence_nr SMALLINT NOT NULL,
    role_code VARCHAR(5),
    assignee_type VARCHAR(20),
    CONSTRAINT pk_patent_assignee PRIMARY KEY (patent_id, sequence_nr)
);

CREATE TABLE patentdb.patent_agent (
    patent_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    sequence_nr SMALLINT NOT NULL,
    rep_type VARCHAR(20),
    internal_ref VARCHAR(100),
    CONSTRAINT pk_patent_agent PRIMARY KEY (patent_id, sequence_nr)
);

CREATE TABLE patentdb.patent_examiner (
    patent_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    examiner_type CHAR(1) NOT NULL,
    department VARCHAR(20),
    sequence_nr SMALLINT NOT NULL,
    CONSTRAINT pk_patent_examiner PRIMARY KEY (patent_id, examiner_type, sequence_nr)
);

CREATE TABLE patentdb.classification (
    scheme_code VARCHAR(10) NOT NULL,
    symbol VARCHAR(30) NOT NULL,
    section CHAR(1),
    class_no VARCHAR(3),
    subclass VARCHAR(2),
    main_group VARCHAR(6),
    subgroup VARCHAR(8),
    version_date DATE,
    edition VARCHAR(10),
    symbol_title VARCHAR(500),
    CONSTRAINT pk_classification PRIMARY KEY (scheme_code, symbol)
);

CREATE TABLE patentdb.patent_classification (
    patent_classification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patent_id BIGINT NOT NULL,
    scheme_code VARCHAR(10) NOT NULL,
    symbol VARCHAR(30) NOT NULL,
    symbol_raw VARCHAR(60),
    position CHAR(1),
    value CHAR(1),
    classification_level CHAR(1),
    generating_office CHAR(2),
    source_type VARCHAR(20) NOT NULL,
    action_date DATE,
    sequence_nr SMALLINT,
    CONSTRAINT pk_patent_classification PRIMARY KEY (patent_classification_id),
    CONSTRAINT uq_patent_classification_business UNIQUE (patent_id,scheme_code,symbol,source_type)
);

CREATE TABLE patentdb.patent_citation (
    citation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    citing_patent_id BIGINT NOT NULL,
    citing_publication_id BIGINT NOT NULL,
    cited_patent_id BIGINT,
    cited_publn_id BIGINT,
    citation_type CHAR(1) NOT NULL,
    cited_country CHAR(2),
    cited_doc_number VARCHAR(30),
    cited_doc_kind VARCHAR(2),
    cited_doc_date DATE,
    cited_doc_date_raw VARCHAR(8),
    cited_doc_name VARCHAR(200),
    cited_appln_nr VARCHAR(30),
    cited_raw_text VARCHAR(500),
    citn_seq INT NOT NULL,
    citn_origin VARCHAR(50),
    citn_gener_auth CHAR(2),
    relevant_claim INT,
    CONSTRAINT pk_patent_citation PRIMARY KEY (citation_id),
    CONSTRAINT uq_patent_citation_source_seq UNIQUE (citing_publication_id,citation_type,citn_seq)
);

CREATE TABLE patentdb.patent_citation_category (
    citation_id BIGINT NOT NULL,
    category_code VARCHAR(10) NOT NULL,
    relevant_claim INT NOT NULL,
    CONSTRAINT pk_patent_citation_category PRIMARY KEY (citation_id, category_code, relevant_claim)
);

CREATE TABLE patentdb.non_patent_citation (
    npl_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    citation_id BIGINT NOT NULL,
    npl_type VARCHAR(10),
    npl_biblio TEXT,
    npl_author VARCHAR(500),
    npl_title VARCHAR(1000),
    npl_editor VARCHAR(500),
    npl_publisher VARCHAR(500),
    npl_volume VARCHAR(50),
    npl_issue VARCHAR(50),
    npl_page_first VARCHAR(50),
    npl_page_last VARCHAR(50),
    npl_publn_date VARCHAR(20),
    npl_doi VARCHAR(500),
    npl_isbn VARCHAR(30),
    npl_issn VARCHAR(30),
    online_availability VARCHAR(500),
    CONSTRAINT pk_non_patent_citation PRIMARY KEY (npl_id),
    CONSTRAINT uq_non_patent_citation_citation_id UNIQUE (citation_id)
);

CREATE TABLE patentdb.patent_family (
    family_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_type VARCHAR(10) NOT NULL,
    source_family_id INT NOT NULL,
    dataset_id BIGINT,
    earliest_priority_date DATE,
    earliest_priority_country CHAR(2),
    representative_publication_id BIGINT,
    note VARCHAR(500),
    CONSTRAINT pk_patent_family PRIMARY KEY (family_id),
    CONSTRAINT uq_patent_family_source UNIQUE (family_type,source_family_id)
);

CREATE TABLE patentdb.patent_family_member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_id BIGINT NOT NULL,
    member_patent_id BIGINT,
    member_seq SMALLINT NOT NULL,
    is_representative CHAR(1),
    member_type VARCHAR(20),
    CONSTRAINT pk_patent_family_member PRIMARY KEY (member_id),
    CONSTRAINT uq_family_member_seq UNIQUE (family_id,member_seq)
);

CREATE TABLE patentdb.family_member_application_ref (
    member_appln_ref_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id BIGINT NOT NULL,
    data_format VARCHAR(20) NOT NULL,
    is_representative CHAR(1),
    doc_id VARCHAR(20),
    country_code CHAR(2),
    appln_nr VARCHAR(50) NOT NULL,
    appln_kind VARCHAR(2),
    CONSTRAINT pk_family_member_application_ref PRIMARY KEY (member_appln_ref_id),
    CONSTRAINT uq_family_app_ref_source UNIQUE (member_id,data_format,appln_nr)
);

CREATE TABLE patentdb.family_member_publication_ref (
    member_publn_ref_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id BIGINT NOT NULL,
    data_format VARCHAR(20) NOT NULL,
    sequence_nr SMALLINT NOT NULL,
    doc_id VARCHAR(20),
    country_code CHAR(2),
    publn_nr VARCHAR(50) NOT NULL,
    publn_kind VARCHAR(2),
    publn_date_raw CHAR(8),
    CONSTRAINT pk_family_member_publication_ref PRIMARY KEY (member_publn_ref_id),
    CONSTRAINT uq_family_pub_ref_source UNIQUE (member_id,data_format,sequence_nr,publn_nr)
);

CREATE TABLE patentdb.family_abstract (
    family_abstract_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_id BIGINT NOT NULL,
    abstract_seq SMALLINT NOT NULL,
    lang_code CHAR(2),
    abstract_text TEXT NOT NULL,
    data_format VARCHAR(20),
    abstract_source VARCHAR(50),
    source_country CHAR(2),
    source_doc_number VARCHAR(50),
    source_kind VARCHAR(2),
    CONSTRAINT pk_family_abstract PRIMARY KEY (family_abstract_id),
    CONSTRAINT uq_family_abstract_seq UNIQUE (family_id,abstract_seq)
);

CREATE TABLE patentdb.priority_claim (
    priority_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patent_id BIGINT NOT NULL,
    prior_patent_id BIGINT,
    sequence_nr SMALLINT NOT NULL,
    prior_country CHAR(2) NOT NULL,
    prior_appln_nr VARCHAR(50) NOT NULL,
    prior_date DATE,
    prior_date_raw CHAR(8),
    priority_kind VARCHAR(20),
    priority_active_indicator CHAR(1),
    designated_region CHAR(2),
    CONSTRAINT pk_priority_claim PRIMARY KEY (priority_id),
    CONSTRAINT uq_priority_patent_seq UNIQUE (patent_id,sequence_nr)
);

CREATE TABLE patentdb.related_application (
    relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patent_id BIGINT NOT NULL,
    related_patent_id BIGINT,
    relation_type VARCHAR(20) NOT NULL,
    related_country CHAR(2),
    related_appln_nr VARCHAR(50),
    related_filing_date DATE,
    related_publn_nr VARCHAR(30),
    parent_status VARCHAR(30),
    sequence_nr SMALLINT NOT NULL,
    CONSTRAINT pk_related_application PRIMARY KEY (relation_id),
    CONSTRAINT uq_related_patent_seq UNIQUE (patent_id,sequence_nr)
);

CREATE TABLE patentdb.international_application (
    int_appln_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patent_id BIGINT NOT NULL,
    int_patent_id BIGINT,
    int_appln_nr VARCHAR(50),
    int_filing_date DATE,
    receiving_office CHAR(2),
    int_publn_nr VARCHAR(30),
    int_publn_date DATE,
    int_lang CHAR(2),
    regional_office CHAR(2),
    national_phase_date DATE,
    CONSTRAINT pk_international_application PRIMARY KEY (int_appln_id),
    CONSTRAINT uq_international_application_patent_id UNIQUE (patent_id)
);

CREATE TABLE patentdb.designated_state (
    patent_id BIGINT NOT NULL,
    state_code CHAR(2) NOT NULL,
    designation_type VARCHAR(10) NOT NULL,
    CONSTRAINT pk_designated_state PRIMARY KEY (patent_id, state_code, designation_type)
);

CREATE TABLE patentdb.legal_status_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patent_id BIGINT NOT NULL,
    dataset_id BIGINT,
    event_seq_nr SMALLINT NOT NULL,
    event_type CHAR(3),
    event_auth CHAR(2) NOT NULL,
    event_code VARCHAR(4) NOT NULL,
    event_filing_date DATE,
    event_publn_date DATE,
    event_effective_date DATE,
    event_text VARCHAR(1000),
    ref_doc_auth CHAR(2),
    ref_doc_nr VARCHAR(20),
    ref_doc_kind VARCHAR(2),
    ref_doc_date DATE,
    lapse_country CHAR(2),
    lapse_date DATE,
    fee_payment_date DATE,
    fee_renewal_year SMALLINT,
    designated_states_raw VARCHAR(1000),
    class_scheme_code VARCHAR(10),
    class_symbol VARCHAR(50),
    CONSTRAINT pk_legal_status_event PRIMARY KEY (event_id),
    CONSTRAINT uq_legal_event_patent_seq UNIQUE (patent_id,event_seq_nr)
);

CREATE TABLE patentdb.patent_keyword (
    patent_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL,
    weight REAL,
    source VARCHAR(50),
    CONSTRAINT pk_patent_keyword PRIMARY KEY (patent_id, keyword_id)
);

CREATE TABLE patentdb.family_citation (
    citing_family_id BIGINT NOT NULL,
    cited_family_id BIGINT NOT NULL,
    CONSTRAINT pk_family_citation PRIMARY KEY (citing_family_id, cited_family_id)
);

-- Foreign keys are added after table creation, including composite references.
ALTER TABLE patentdb.dataset ADD CONSTRAINT fk_dataset_office_code FOREIGN KEY (office_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.kind_code ADD CONSTRAINT fk_kind_code_office_code FOREIGN KEY (office_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.classification_scheme ADD CONSTRAINT fk_classification_scheme_authority FOREIGN KEY (authority) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.legal_event_code ADD CONSTRAINT fk_legal_event_code_event_auth FOREIGN KEY (event_auth) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.keyword ADD CONSTRAINT fk_keyword_lang_code FOREIGN KEY (lang_code) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.patent ADD CONSTRAINT fk_patent_dataset_id FOREIGN KEY (dataset_id) REFERENCES patentdb.dataset (dataset_id);
ALTER TABLE patentdb.patent ADD CONSTRAINT fk_patent_appln_auth FOREIGN KEY (appln_auth) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.patent ADD CONSTRAINT fk_patent_appl_type_code FOREIGN KEY (appl_type_code) REFERENCES patentdb.application_type (appl_type_code);
ALTER TABLE patentdb.patent ADD CONSTRAINT fk_patent_receiving_office FOREIGN KEY (receiving_office) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.patent ADD CONSTRAINT fk_patent_appln_lang FOREIGN KEY (appln_lang) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.publication ADD CONSTRAINT fk_publication_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id);
ALTER TABLE patentdb.publication ADD CONSTRAINT fk_publication_dataset_id FOREIGN KEY (dataset_id) REFERENCES patentdb.dataset (dataset_id);
ALTER TABLE patentdb.publication ADD CONSTRAINT fk_publication_publn_auth FOREIGN KEY (publn_auth) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.publication ADD CONSTRAINT fk_publication_kind_code FOREIGN KEY (publn_auth, publn_kind) REFERENCES patentdb.kind_code (office_code, kind_code);
ALTER TABLE patentdb.publication ADD CONSTRAINT fk_publication_publn_lg FOREIGN KEY (publn_lg) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.title ADD CONSTRAINT fk_title_publication_id FOREIGN KEY (publication_id) REFERENCES patentdb.publication (publication_id) ON DELETE CASCADE;
ALTER TABLE patentdb.title ADD CONSTRAINT fk_title_lang_code FOREIGN KEY (lang_code) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.abstract ADD CONSTRAINT fk_abstract_publication_id FOREIGN KEY (publication_id) REFERENCES patentdb.publication (publication_id) ON DELETE CASCADE;
ALTER TABLE patentdb.abstract ADD CONSTRAINT fk_abstract_lang_code FOREIGN KEY (lang_code) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.description_section ADD CONSTRAINT fk_description_section_publication_id FOREIGN KEY (publication_id) REFERENCES patentdb.publication (publication_id) ON DELETE CASCADE;
ALTER TABLE patentdb.description_section ADD CONSTRAINT fk_description_section_parent_section_id FOREIGN KEY (parent_section_id) REFERENCES patentdb.description_section (section_id);
ALTER TABLE patentdb.drawing ADD CONSTRAINT fk_drawing_publication_id FOREIGN KEY (publication_id) REFERENCES patentdb.publication (publication_id) ON DELETE CASCADE;
ALTER TABLE patentdb.claim ADD CONSTRAINT fk_claim_publication_id FOREIGN KEY (publication_id) REFERENCES patentdb.publication (publication_id) ON DELETE CASCADE;
ALTER TABLE patentdb.claim ADD CONSTRAINT fk_claim_lang_code FOREIGN KEY (lang_code) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.claim_dependency ADD CONSTRAINT fk_claim_dependency_dependent_claim_id FOREIGN KEY (dependent_claim_id) REFERENCES patentdb.claim (claim_id) ON DELETE CASCADE;
ALTER TABLE patentdb.claim_dependency ADD CONSTRAINT fk_claim_dependency_parent_claim_id FOREIGN KEY (parent_claim_id) REFERENCES patentdb.claim (claim_id) ON DELETE CASCADE;
ALTER TABLE patentdb.person ADD CONSTRAINT fk_person_ctry_code FOREIGN KEY (ctry_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.person ADD CONSTRAINT fk_person_residence_ctry_code FOREIGN KEY (residence_ctry_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.person ADD CONSTRAINT fk_person_source_dataset_id FOREIGN KEY (source_dataset_id) REFERENCES patentdb.dataset (dataset_id);
ALTER TABLE patentdb.natural_person ADD CONSTRAINT fk_natural_person_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id) ON DELETE CASCADE;
ALTER TABLE patentdb.organization ADD CONSTRAINT fk_organization_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_applicant ADD CONSTRAINT fk_patent_applicant_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_applicant ADD CONSTRAINT fk_patent_applicant_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id);
ALTER TABLE patentdb.patent_inventor ADD CONSTRAINT fk_patent_inventor_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_inventor ADD CONSTRAINT fk_patent_inventor_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id);
ALTER TABLE patentdb.patent_assignee ADD CONSTRAINT fk_patent_assignee_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_assignee ADD CONSTRAINT fk_patent_assignee_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id);
ALTER TABLE patentdb.patent_agent ADD CONSTRAINT fk_patent_agent_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_agent ADD CONSTRAINT fk_patent_agent_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id);
ALTER TABLE patentdb.patent_examiner ADD CONSTRAINT fk_patent_examiner_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_examiner ADD CONSTRAINT fk_patent_examiner_person_id FOREIGN KEY (person_id) REFERENCES patentdb.person (person_id);
ALTER TABLE patentdb.classification ADD CONSTRAINT fk_classification_scheme_code FOREIGN KEY (scheme_code) REFERENCES patentdb.classification_scheme (scheme_code);
ALTER TABLE patentdb.patent_classification ADD CONSTRAINT fk_patent_classification_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_classification ADD CONSTRAINT fk_patent_classification_class FOREIGN KEY (scheme_code, symbol) REFERENCES patentdb.classification (scheme_code, symbol);
ALTER TABLE patentdb.patent_classification ADD CONSTRAINT fk_patent_classification_generating_office FOREIGN KEY (generating_office) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT fk_patent_citation_citing_patent_id FOREIGN KEY (citing_patent_id) REFERENCES patentdb.patent (patent_id);
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT fk_patent_citation_citing_publication_id FOREIGN KEY (citing_publication_id) REFERENCES patentdb.publication (publication_id);
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT fk_patent_citation_cited_patent_id FOREIGN KEY (cited_patent_id) REFERENCES patentdb.patent (patent_id);
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT fk_patent_citation_cited_publn_id FOREIGN KEY (cited_publn_id) REFERENCES patentdb.publication (publication_id);
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT fk_patent_citation_cited_country FOREIGN KEY (cited_country) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT fk_patent_citation_citn_gener_auth FOREIGN KEY (citn_gener_auth) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.patent_citation_category ADD CONSTRAINT fk_patent_citation_category_citation_id FOREIGN KEY (citation_id) REFERENCES patentdb.patent_citation (citation_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_citation_category ADD CONSTRAINT fk_patent_citation_category_category_code FOREIGN KEY (category_code) REFERENCES patentdb.citation_category (category_code);
ALTER TABLE patentdb.non_patent_citation ADD CONSTRAINT fk_non_patent_citation_citation_id FOREIGN KEY (citation_id) REFERENCES patentdb.patent_citation (citation_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_family ADD CONSTRAINT fk_patent_family_dataset_id FOREIGN KEY (dataset_id) REFERENCES patentdb.dataset (dataset_id);
ALTER TABLE patentdb.patent_family ADD CONSTRAINT fk_patent_family_earliest_priority_country FOREIGN KEY (earliest_priority_country) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.patent_family ADD CONSTRAINT fk_patent_family_representative_publication_id FOREIGN KEY (representative_publication_id) REFERENCES patentdb.publication (publication_id);
ALTER TABLE patentdb.patent_family_member ADD CONSTRAINT fk_patent_family_member_family_id FOREIGN KEY (family_id) REFERENCES patentdb.patent_family (family_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_family_member ADD CONSTRAINT fk_patent_family_member_member_patent_id FOREIGN KEY (member_patent_id) REFERENCES patentdb.patent (patent_id);
ALTER TABLE patentdb.family_member_application_ref ADD CONSTRAINT fk_family_member_application_ref_member_id FOREIGN KEY (member_id) REFERENCES patentdb.patent_family_member (member_id) ON DELETE CASCADE;
ALTER TABLE patentdb.family_member_application_ref ADD CONSTRAINT fk_family_member_application_ref_country_code FOREIGN KEY (country_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.family_member_publication_ref ADD CONSTRAINT fk_family_member_publication_ref_member_id FOREIGN KEY (member_id) REFERENCES patentdb.patent_family_member (member_id) ON DELETE CASCADE;
ALTER TABLE patentdb.family_member_publication_ref ADD CONSTRAINT fk_family_member_publication_ref_country_code FOREIGN KEY (country_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.family_abstract ADD CONSTRAINT fk_family_abstract_family_id FOREIGN KEY (family_id) REFERENCES patentdb.patent_family (family_id) ON DELETE CASCADE;
ALTER TABLE patentdb.family_abstract ADD CONSTRAINT fk_family_abstract_lang_code FOREIGN KEY (lang_code) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.family_abstract ADD CONSTRAINT fk_family_abstract_source_country FOREIGN KEY (source_country) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.priority_claim ADD CONSTRAINT fk_priority_claim_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.priority_claim ADD CONSTRAINT fk_priority_claim_prior_patent_id FOREIGN KEY (prior_patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.priority_claim ADD CONSTRAINT fk_priority_claim_prior_country FOREIGN KEY (prior_country) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.priority_claim ADD CONSTRAINT fk_priority_claim_designated_region FOREIGN KEY (designated_region) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.related_application ADD CONSTRAINT fk_related_application_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.related_application ADD CONSTRAINT fk_related_application_related_patent_id FOREIGN KEY (related_patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.related_application ADD CONSTRAINT fk_related_application_related_country FOREIGN KEY (related_country) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.international_application ADD CONSTRAINT fk_international_application_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.international_application ADD CONSTRAINT fk_international_application_int_patent_id FOREIGN KEY (int_patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.international_application ADD CONSTRAINT fk_international_application_receiving_office FOREIGN KEY (receiving_office) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.international_application ADD CONSTRAINT fk_international_application_int_lang FOREIGN KEY (int_lang) REFERENCES patentdb.language (lang_code);
ALTER TABLE patentdb.international_application ADD CONSTRAINT fk_international_application_regional_office FOREIGN KEY (regional_office) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.designated_state ADD CONSTRAINT fk_designated_state_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.designated_state ADD CONSTRAINT fk_designated_state_state_code FOREIGN KEY (state_code) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_dataset_id FOREIGN KEY (dataset_id) REFERENCES patentdb.dataset (dataset_id);
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_event_auth FOREIGN KEY (event_auth) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_code FOREIGN KEY (event_auth, event_code) REFERENCES patentdb.legal_event_code (event_auth, event_code);
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_ref_doc_auth FOREIGN KEY (ref_doc_auth) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_lapse_country FOREIGN KEY (lapse_country) REFERENCES patentdb.country_office (ctry_code);
ALTER TABLE patentdb.legal_status_event ADD CONSTRAINT fk_legal_status_event_class_scheme_code FOREIGN KEY (class_scheme_code) REFERENCES patentdb.classification_scheme (scheme_code);
ALTER TABLE patentdb.patent_keyword ADD CONSTRAINT fk_patent_keyword_patent_id FOREIGN KEY (patent_id) REFERENCES patentdb.patent (patent_id) ON DELETE CASCADE;
ALTER TABLE patentdb.patent_keyword ADD CONSTRAINT fk_patent_keyword_keyword_id FOREIGN KEY (keyword_id) REFERENCES patentdb.keyword (keyword_id);
ALTER TABLE patentdb.family_citation ADD CONSTRAINT fk_family_citation_citing_family_id FOREIGN KEY (citing_family_id) REFERENCES patentdb.patent_family (family_id) ON DELETE CASCADE;
ALTER TABLE patentdb.family_citation ADD CONSTRAINT fk_family_citation_cited_family_id FOREIGN KEY (cited_family_id) REFERENCES patentdb.patent_family (family_id) ON DELETE CASCADE;

-- Supporting indexes; PostgreSQL does not create indexes on referencing columns automatically.
CREATE INDEX ix_dataset_office_code ON patentdb.dataset (office_code);
CREATE INDEX ix_classification_scheme_authority ON patentdb.classification_scheme (authority);
CREATE INDEX ix_keyword_lang_code ON patentdb.keyword (lang_code);
CREATE INDEX ix_patent_dataset_id ON patentdb.patent (dataset_id);
CREATE INDEX ix_patent_appln_auth ON patentdb.patent (appln_auth);
CREATE INDEX ix_patent_appl_type_code ON patentdb.patent (appl_type_code);
CREATE INDEX ix_patent_receiving_office ON patentdb.patent (receiving_office);
CREATE INDEX ix_patent_appln_lang ON patentdb.patent (appln_lang);
CREATE INDEX ix_publication_patent_id ON patentdb.publication (patent_id);
CREATE INDEX ix_publication_dataset_id ON patentdb.publication (dataset_id);
CREATE INDEX ix_publication_publn_auth ON patentdb.publication (publn_auth);
CREATE INDEX ix_publication_publn_kind ON patentdb.publication (publn_kind);
CREATE INDEX ix_publication_publn_lg ON patentdb.publication (publn_lg);
CREATE INDEX ix_title_publication_id ON patentdb.title (publication_id);
CREATE INDEX ix_title_lang_code ON patentdb.title (lang_code);
CREATE INDEX ix_abstract_publication_id ON patentdb.abstract (publication_id);
CREATE INDEX ix_abstract_lang_code ON patentdb.abstract (lang_code);
CREATE INDEX ix_description_section_publication_id ON patentdb.description_section (publication_id);
CREATE INDEX ix_description_section_parent_section_id ON patentdb.description_section (parent_section_id);
CREATE INDEX ix_drawing_publication_id ON patentdb.drawing (publication_id);
CREATE INDEX ix_claim_publication_id ON patentdb.claim (publication_id);
CREATE INDEX ix_claim_lang_code ON patentdb.claim (lang_code);
CREATE INDEX ix_person_ctry_code ON patentdb.person (ctry_code);
CREATE INDEX ix_person_residence_ctry_code ON patentdb.person (residence_ctry_code);
CREATE INDEX ix_person_source_dataset_id ON patentdb.person (source_dataset_id);
CREATE INDEX ix_patent_applicant_person_id ON patentdb.patent_applicant (person_id);
CREATE INDEX ix_patent_inventor_person_id ON patentdb.patent_inventor (person_id);
CREATE INDEX ix_patent_assignee_person_id ON patentdb.patent_assignee (person_id);
CREATE INDEX ix_patent_agent_person_id ON patentdb.patent_agent (person_id);
CREATE INDEX ix_patent_examiner_person_id ON patentdb.patent_examiner (person_id);
CREATE INDEX ix_patent_classification_patent_id ON patentdb.patent_classification (patent_id);
CREATE INDEX ix_patent_classification_generating_office ON patentdb.patent_classification (generating_office);
CREATE INDEX ix_patent_citation_citing_patent_id ON patentdb.patent_citation (citing_patent_id);
CREATE INDEX ix_patent_citation_citing_publication_id ON patentdb.patent_citation (citing_publication_id);
CREATE INDEX ix_patent_citation_cited_patent_id ON patentdb.patent_citation (cited_patent_id);
CREATE INDEX ix_patent_citation_cited_publn_id ON patentdb.patent_citation (cited_publn_id);
CREATE INDEX ix_patent_citation_cited_country ON patentdb.patent_citation (cited_country);
CREATE INDEX ix_patent_citation_citn_gener_auth ON patentdb.patent_citation (citn_gener_auth);
CREATE INDEX ix_non_patent_citation_citation_id ON patentdb.non_patent_citation (citation_id);
CREATE INDEX ix_patent_family_dataset_id ON patentdb.patent_family (dataset_id);
CREATE INDEX ix_patent_family_earliest_priority_country ON patentdb.patent_family (earliest_priority_country);
CREATE INDEX ix_patent_family_representative_publication_id ON patentdb.patent_family (representative_publication_id);
CREATE INDEX ix_patent_family_member_family_id ON patentdb.patent_family_member (family_id);
CREATE INDEX ix_patent_family_member_member_patent_id ON patentdb.patent_family_member (member_patent_id);
CREATE INDEX ix_family_member_application_ref_member_id ON patentdb.family_member_application_ref (member_id);
CREATE INDEX ix_family_member_application_ref_country_code ON patentdb.family_member_application_ref (country_code);
CREATE INDEX ix_family_member_publication_ref_member_id ON patentdb.family_member_publication_ref (member_id);
CREATE INDEX ix_family_member_publication_ref_country_code ON patentdb.family_member_publication_ref (country_code);
CREATE INDEX ix_family_abstract_family_id ON patentdb.family_abstract (family_id);
CREATE INDEX ix_family_abstract_lang_code ON patentdb.family_abstract (lang_code);
CREATE INDEX ix_family_abstract_source_country ON patentdb.family_abstract (source_country);
CREATE INDEX ix_priority_claim_patent_id ON patentdb.priority_claim (patent_id);
CREATE INDEX ix_priority_claim_prior_patent_id ON patentdb.priority_claim (prior_patent_id);
CREATE INDEX ix_priority_claim_prior_country ON patentdb.priority_claim (prior_country);
CREATE INDEX ix_priority_claim_designated_region ON patentdb.priority_claim (designated_region);
CREATE INDEX ix_related_application_patent_id ON patentdb.related_application (patent_id);
CREATE INDEX ix_related_application_related_patent_id ON patentdb.related_application (related_patent_id);
CREATE INDEX ix_related_application_related_country ON patentdb.related_application (related_country);
CREATE INDEX ix_international_application_patent_id ON patentdb.international_application (patent_id);
CREATE INDEX ix_international_application_int_patent_id ON patentdb.international_application (int_patent_id);
CREATE INDEX ix_international_application_receiving_office ON patentdb.international_application (receiving_office);
CREATE INDEX ix_international_application_int_lang ON patentdb.international_application (int_lang);
CREATE INDEX ix_international_application_regional_office ON patentdb.international_application (regional_office);
CREATE INDEX ix_legal_status_event_patent_id ON patentdb.legal_status_event (patent_id);
CREATE INDEX ix_legal_status_event_dataset_id ON patentdb.legal_status_event (dataset_id);
CREATE INDEX ix_legal_status_event_event_auth ON patentdb.legal_status_event (event_auth);
CREATE INDEX ix_legal_status_event_ref_doc_auth ON patentdb.legal_status_event (ref_doc_auth);
CREATE INDEX ix_legal_status_event_lapse_country ON patentdb.legal_status_event (lapse_country);
CREATE INDEX ix_legal_status_event_class_scheme_code ON patentdb.legal_status_event (class_scheme_code);
CREATE INDEX ix_patent_appln_nr_epodoc ON patentdb.patent (appln_nr_epodoc);
CREATE INDEX ix_patent_appln_filing_date ON patentdb.patent (appln_filing_date);
CREATE INDEX ix_publication_publn_date ON patentdb.publication (publn_date);
CREATE INDEX ix_patent_classification_symbol ON patentdb.patent_classification (symbol);
CREATE INDEX ix_patent_classification_scheme_code ON patentdb.patent_classification (scheme_code);
CREATE INDEX ix_patent_citation_cited_doc_number ON patentdb.patent_citation (cited_doc_number);
CREATE INDEX ix_patent_family_earliest_priority_date ON patentdb.patent_family (earliest_priority_date);
CREATE INDEX ix_legal_status_event_event_effective_date ON patentdb.legal_status_event (event_effective_date);
CREATE INDEX ix_legal_status_event_event_code ON patentdb.legal_status_event (event_code);

-- Domain checks based on documented code values.
ALTER TABLE patentdb.kind_code ADD CONSTRAINT ck_kind_code_publication_level CHECK (publication_level IS NULL OR publication_level IN ('1', '2', '3'));
ALTER TABLE patentdb.patent ADD CONSTRAINT ck_patent_int_phase CHECK (int_phase IN ('Y', 'N'));
ALTER TABLE patentdb.patent ADD CONSTRAINT ck_patent_reg_phase CHECK (reg_phase IN ('Y', 'N'));
ALTER TABLE patentdb.patent ADD CONSTRAINT ck_patent_nat_phase CHECK (nat_phase IN ('Y', 'N'));
ALTER TABLE patentdb.publication ADD CONSTRAINT ck_publication_first_grant CHECK (publn_first_grant IS NULL OR publn_first_grant IN ('Y', 'N'));
ALTER TABLE patentdb.person ADD CONSTRAINT ck_person_type CHECK (person_type IN ('N', 'L'));
ALTER TABLE patentdb.organization ADD CONSTRAINT ck_organization_psn_sector CHECK (psn_sector IS NULL OR psn_sector IN ('COMPANY', 'GOV', 'UNIVERSITY', 'NONPROFIT'));
ALTER TABLE patentdb.patent_citation ADD CONSTRAINT ck_patent_citation_type CHECK (citation_type IN ('P', 'N'));
ALTER TABLE patentdb.patent_family_member ADD CONSTRAINT ck_family_member_representative CHECK (is_representative IS NULL OR is_representative IN ('Y', 'N'));

-- Enforce person ISA: each person must have exactly one matching subtype.
CREATE OR REPLACE FUNCTION patentdb.check_person_isa() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_person_id BIGINT;
    v_type CHAR(1);
    v_natural BOOLEAN;
    v_org BOOLEAN;
BEGIN
    v_person_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.person_id ELSE NEW.person_id END;
    SELECT person_type INTO v_type FROM patentdb.person WHERE person_id = v_person_id;
    IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT EXISTS (SELECT 1 FROM patentdb.natural_person WHERE person_id = v_person_id),
           EXISTS (SELECT 1 FROM patentdb.organization WHERE person_id = v_person_id)
      INTO v_natural, v_org;
    IF (v_type = 'N' AND v_natural AND NOT v_org) OR (v_type = 'L' AND v_org AND NOT v_natural) THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION 'person % must have exactly one subtype matching person_type %', v_person_id, v_type;
END;
$$;
CREATE CONSTRAINT TRIGGER ct_person_isa AFTER INSERT OR UPDATE OR DELETE ON patentdb.person DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION patentdb.check_person_isa();
CREATE CONSTRAINT TRIGGER ct_natural_person_isa AFTER INSERT OR UPDATE OR DELETE ON patentdb.natural_person DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION patentdb.check_person_isa();
CREATE CONSTRAINT TRIGGER ct_organization_isa AFTER INSERT OR UPDATE OR DELETE ON patentdb.organization DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION patentdb.check_person_isa();

COMMIT;
