#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 INID 码对照表（CSV + Markdown 片段）。

INID 含义依据：WIPO ST.9（2024-10，页码 3.9.4–3.9.7）。
USPTO XML 路径依据：sources/samples 下真实样例的解析结果（见 XML结构解析报告.md）。
DOCDB 字段依据：PATSTAT 第三方镜像（来源清单 W6/W7）。

用法：python3 gen_inid_table.py <out_csv> <out_md>
"""
import csv
import sys

# INID 码, 英文含义, 中文含义, USPTO XML 路径(样例验证), DOCDB/PATSTAT 参照, 本设计实体.属性, 备注
ROWS = [
    ("10", "Identification of the patent, SPC or patent document (category)",
     "专利/SPC/文献标识（大类）", "publication-reference", "tls211_pat_publn",
     "publication（分组标识）", "ST.9 中(11)(13)(19)组合时可用(10)；本设计不单独建字段"),
    ("11", "Number of the patent, SPC or patent document",
     "专利/文献号", "us-bibliographic-data-*/publication-reference/document-id/doc-number",
     "tls211_pat_publn.publn_nr", "publication.publn_nr", "与(19)局代码、(13)种类码联合唯一"),
    ("12", "Plain language designation of the kind of document",
     "文献种类文字说明", "（无独立元素，kind 的文字含义见 ST.16）", "tls211_pat_publn.publn_kind",
     "kind_code.kind_description_en/cn", "由 kind 码查维表得到，不冗余存储"),
    ("13", "Kind-of-document code according to WIPO Standard ST.16",
     "文献种类代码（ST.16）", "publication-reference/document-id/kind",
     "tls211_pat_publn.publn_kind", "publication.publn_kind → kind_code",
     "如 A1（申请公布）、B1/B2（授权公告）、S1（外观设计）"),
    ("15", "Patent correction information", "专利更正信息",
     "（样例未见；DTD 中有相关更正元素）", "—", "暂不建模（局限）",
     "ST.9 注：更正按 ST.50；本阶段列入边界外，待手册确认"),
    ("19", "WIPO Standard ST.3 code of the publishing office/organization",
     "公布局/组织代码（ST.3）", "publication-reference/document-id/country",
     "tls211_pat_publn.publn_auth", "publication.publn_auth → country_office",
     "US/EP/WO 等两位代码"),
    ("21", "Number(s) assigned to the application(s)", "申请号",
     "application-reference/document-id/doc-number", "tls201_appln.appln_nr",
     "patent.appln_nr", "配合 appln_auth/appln_kind；另有 appln_nr_original"),
    ("22", "Date(s) of filing the application(s)", "申请日",
     "application-reference/document-id/date", "tls201_appln.appln_filing_date",
     "patent.appln_filing_date", "YYYYMMDD；存 DATE"),
    ("23", "Other date(s) (e.g. filing complete spec., exhibition date)",
     "其他日期（完整说明书提交日/展出日等）", "（样例未见独立元素）", "tls201_appln（无直接列）",
     "patent 备注/related_application", "本阶段仅有选择地保留（见待确认清单）"),
    ("24", "Date from which industrial property rights may have effect",
     "权利生效日", "（授权数据中可由授权公告日+法律状态推导）",
     "tls231_inpadoc_legal_event.event_effective_date", "legal_status_event.event_effective_date",
     "用法律状态事件承接"),
    ("25", "Language in which the published application was originally filed",
     "申请原始语言", "根元素 lang（如 EN）", "tls201（原语言字段）",
     "patent/appln_lang → language", "本阶段保留在 patent.lang_code（可选列）"),
    ("26", "Language in which the application is published", "公布语言",
     "根元素 lang", "tls211_pat_publn.publn_lg", "publication.publn_lg → language",
     "EP 数据有 EN/DE/FR"),
    ("30", "Data relating to priority under the Paris Convention/TRIPS (category)",
     "优先权数据（大类）", "priority-claims/priority-claim", "tls204_appln_prior",
     "priority_claim（分组）", "本设计按(31)(32)(33)拆列存储"),
    ("31", "Number(s) assigned to priority application(s)", "优先权申请号",
     "priority-claims/priority-claim/doc-number", "tls204_appln_prior.prior_appln_id→tls201.appln_nr",
     "priority_claim.prior_appln_nr", "可为外部局号码（如 JP 2019-239059）"),
    ("32", "Date(s) of filing of priority application(s)", "优先权申请日",
     "priority-claims/priority-claim/date", "tls201_appln.appln_filing_date（prior）",
     "priority_claim.prior_date", "YYYYMMDD"),
    ("33", "ST.3 code of office allotting the priority application number",
     "优先权受理局代码", "priority-claims/priority-claim/country",
     "tls201_appln.appln_auth（prior）", "priority_claim.prior_country → country_office",
     "如 JP/DE/US"),
    ("34", "ST.3 code identifying at least one country party to Paris Convention for regional/international priority filings",
     "区域/国际优先权的缔约国代码", "priority-claim[@kind='regional'/'international']（样例为 national）",
     "—", "priority_claim.designated_region（可选列）", "仅区域/国际优先权使用"),
    ("40", "Date(s) of making available to the public (category)", "公开日期（大类）",
     "publication-reference/document-id/date", "tls211_pat_publn.publn_date",
     "publication.publn_date", "具体级别由 kind 区分(41)–(47)"),
    ("43", "Date of making public an unexamined patent document by printing",
     "未审查文献印刷公布日（申请公布）", "申请数据 publication-reference/date + kind=A1",
     "tls211_pat_publn.publn_date", "publication.publn_date（kind=A1）", "美国申请公布"),
    ("45", "Date of making public a patent document on which grant has taken place",
     "授权公告日", "授权数据 publication-reference/date + kind=B1/B2",
     "tls211_pat_publn.publn_date", "publication.publn_date（kind=B1/B2）", "美国授权公告"),
    ("46", "Date of making available the claim(s) only", "仅权利要求的公布日",
     "（样例未见）", "—", "publication.publn_date（特殊 kind）", "边界外，待手册确认"),
    ("47", "Date of making public by viewing/copying a granted document", "授权文献查阅公开日",
     "（样例未见）", "—", "publication.publn_date（特殊 kind）", "边界外"),
    ("48", "Date of issuance of a corrected patent document", "更正文献发行日",
     "（样例未见）", "—", "暂不建模（局限）", "与(15)相关"),
    ("51", "International Patent Classification (IPC)", "国际专利分类号",
     "classifications-ipcr/classification-ipcr/{section,class,subclass,main-group,subgroup}",
     "tls209_appln_ipc.ipc_class_symbol", "patent_classification（scheme=IPC）",
     "另存 symbol-position/classification-value/level/version 等角色字段"),
    ("52", "Domestic or national classification", "国家/本局分类号",
     "classification-national/{country,main-classification,further-classification}；设计数据 classification-locarno",
     "tls210_appln_n_cls.nat_class_symbol", "patent_classification（scheme=USPC/LOCARNO）",
     "美国发明用 USPC，外观设计用洛迦诺"),
    ("53", "Universal Decimal Classification", "国际十进分类（已删除）",
     "—", "—", "不建模", "ST.9 修订记录：1997-11-21 删除"),
    ("54", "Title of the invention", "发明名称",
     "us-bibliographic-data-*/invention-title", "tls202_appln_title.appln_title",
     "title.title_text（含 lang）", "多语言时多行"),
    ("55", "Keywords", "关键词（已删除）",
     "（样例未见）", "—", "keyword + patent_keyword（增强表）",
     "ST.9 修订记录：1997-11-21 删除；为承接部分数据源仍保留关键词表"),
    ("56", "List of prior art documents, if separate from descriptive text",
     "现有技术文献列表（引用）", "us-references-cited/us-citation（patcit/nplcit/category）",
     "tls212_citation + tls214_npl_publn + tls215_citn_categ",
     "patent_citation + non_patent_citation + citation_category", "含审查员/申请人引用类别"),
    ("57", "Abstract or claim", "摘要或权利要求",
     "abstract/p；claims/claim/claim-text", "tls203_appln_abstr.appln_abstract",
     "abstract + claim", "本设计分开建模，不做二选一"),
    ("58", "Field of search", "检索领域",
     "us-field-of-classification-search/classification-national",
     "tls210_appln_n_cls（常合并）", "patent_classification.source_type='search_field'",
     "以角色字段区分检索领域与正式分类"),
    ("60", "References to other legally/procedurally related domestic patent documents (category)",
     "法律/程序关联文献（大类）", "us-related-documents（DTD 元素，样例未见）", "tls216_appln_contn",
     "related_application（分组）", "61–68 分别对应不同类型"),
    ("61", "Earlier application to which present document is an addition", "增补（addition）关系",
     "us-related-documents/us-addition（DTD）", "tls216_appln_contn.contn_type",
     "related_application（relation_type='addition'）", "样例未见，待手册确认"),
    ("62", "Earlier application from which present document has been divided up", "分案（division）",
     "us-related-documents/us-divisional（DTD）", "tls216_appln_contn.contn_type",
     "related_application（relation_type='division'）", "美国常见"),
    ("63", "Earlier application of which present is a continuation", "继续（continuation/CIP）",
     "us-related-documents/us-continuation（DTD）", "tls216_appln_contn.contn_type",
     "related_application（relation_type='continuation'）", "美国常见"),
    ("64", "Number of the earlier publication which is reissued", "再颁（reissue）",
     "us-related-documents/us-reissue（DTD）", "tls216_appln_contn.contn_type",
     "related_application（relation_type='reissue'）", "美国常见"),
    ("65", "Number of a previously published patent document concerning the same application",
     "同一申请先前公布的文献号", "（可由 publication 表内多行体现）", "tls211_pat_publn（同 appln_id 多行）",
     "publication（同一 patent 的多个 publication）", "不另建关系，1:N 自然表达"),
    ("66", "Earlier application of which present is a substitute", "替代申请（substitute）",
     "us-related-documents（DTD）", "tls216_appln_contn.contn_type",
     "related_application（relation_type='substitution'）", "—"),
    ("67", "Patent/application on which utility model is based", "实用新型基础申请",
     "（美国数据无；JP/DE 数据有）", "—", "related_application（可扩展类型）", "边界外，保留扩展位"),
    ("68", "For an SPC, number of the basic patent", "SPC 基础专利号",
     "（美/欧全文数据无 SPC）", "—", "不建模", "SPC 数据不在本次四类数据范围"),
    ("70", "Identification of parties concerned (category)", "当事人标识（大类）",
     "us-parties/assignees/agents/examiners", "tls206_person + tls207_pers_appln",
     "person + 各角色关联表", "71–76 由角色表区分"),
    ("71", "Name(s) of applicant(s)", "申请人姓名/名称",
     "us-parties/us-applicants/us-applicant/addressbook", "tls207_pers_appln（applt_seq_nr>0）",
     "patent_applicant + person", "含自然人/机构"),
    ("72", "Name(s) of inventor(s)", "发明人姓名",
     "us-parties/inventors/inventor/addressbook", "tls207_pers_appln（invt_seq_nr>0）",
     "patent_inventor + person", "—"),
    ("73", "Name(s) of grantee(s)/assignee(s)/owner(s)", "专利权人/受让人",
     "assignees/assignee/addressbook（含 role）", "tls227_pers_publn（授权层）",
     "patent_assignee + person", "与申请人的差别体现在关联表"),
    ("74", "Name(s) of attorney(s) or agent(s)", "代理人/代理机构",
     "us-parties/agents/agent[@rep-type]/addressbook", "tls206_person（代理机构/人）",
     "patent_agent + person", "机构用 orgname"),
    ("75", "Name(s) of inventor(s) who is/are also applicant(s)", "发明人兼申请人",
     "同一 addressbook 同时出现在 inventors 与 us-applicants（样例中 WU Weinan 即此情形）",
     "tls207_pers_appln（invt_seq_nr 与 applt_seq_nr 同号）", "person + 两张关联表",
     "不建新表，用角色重叠表达"),
    ("76", "Name(s) of inventor(s) who is/are also applicant(s) and grantee(s)",
     "发明人兼申请人兼权利人", "同上 + assignees", "tls207_pers_appln + tls227_pers_publn",
     "person + 三张关联表", "不建新表"),
    ("81", "Designated State(s) according to the PCT", "PCT 指定国",
     "pct-or-regional-filing-data（部分体现）", "tls231_inpadoc_legal_event.designated_states",
     "designated_state（增强表）", "EP/PCT 数据必要"),
    ("84", "Designated Contracting States under regional patent conventions", "区域公约指定国",
     "EP 数据（DOCDB）", "tls231_inpadoc_legal_event.designated_states",
     "designated_state（designation_type='EP'）", "EP 数据必要"),
    ("85", "Date of commencement of the national phase pursuant to PCT Art.23(1)/40(1)",
     "进入国家阶段日", "pct-or-regional-filing-data/us-371c12-date/date",
     "tls201_appln（int/reg/nat_phase 相关）", "international_application.national_phase_date",
     "样例值 20220527"),
    ("86", "Filing data of the PCT international application", "PCT 国际申请数据",
     "pct-or-regional-filing-data/document-id/{country,doc-number,date}",
     "tls201_appln.internat_appln_id", "international_application.int_appln_nr/int_filing_date",
     "样例 PCT/JP2020/033620，2020-09-04"),
    ("87", "Publication data of the PCT international application", "PCT 国际公布数据",
     "（样例未见；DTD/EP 数据有）", "tls211_pat_publn（WO 公布）",
     "international_application.int_publn_nr/int_publn_date", "待手册确认"),
    ("88", "Date of deferred publication of the search report", "检索报告延迟公布日",
     "（样例未见）", "—", "publication（特殊 kind）", "边界外"),
    ("91", "Date on which PCT application no longer has effect in designated States",
     "PCT 失效日", "（样例未见）", "tls231_inpadoc_legal_event",
     "legal_status_event", "用法律状态事件承接"),
    ("96", "Filing data of the regional application", "区域申请数据（EP）",
     "EP 全文/DOCDB 数据", "tls201_appln（regional）", "international_application（EP）", "EP 数据必要"),
    ("97", "Publication data of the regional application/patent", "区域公布数据（EP）",
     "EP 全文/DOCDB 数据", "tls211_pat_publn", "publication（EP A1/B1 等）", "EP 数据必要"),
    ("98", "For an SPC, dates concerning extension/revocation/recalculation", "SPC 期限相关日期",
     "（不在本次数据范围）", "—", "不建模", "边界外"),
]



# 官网手册补充: INID -> (EP B 元素, DOCDB/Exchange 元素, 官网手册依据)
# 页码一律是 PDF 文件页码（从 1 起），不是页脚印刷号；四份手册的页脚
# 存在重复/错乱，使用 PDF 页码才可复现。
EXTRA = {
    "10": ("B100", "publication-reference", "EP全文手册 PDF p.5–9（B100）；DOCDB手册 PDF p.6–7"),
    "11": ("B110", "publication-reference/document-id/doc-number", "EP全文手册 PDF p.5–9（B110）；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "12": ("B120（B121 文字）", "—", "EP全文手册 PDF p.5–9（B120/B121）"),
    "13": ("B130", "publication-reference/document-id/kind", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；ST.16"),
    "15": ("B150／B665（更正信息）", "—", "EP全文手册 PDF p.5–9（B150）"),
    "19": ("B190", "@country / @originating-office", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "21": ("B210／B210EP／B211EP", "application-reference/document-id", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5"),
    "22": ("B220", "application-reference/document-id/date", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5"),
    "23": ("B230", "—", "EP全文手册 PDF p.5–9"),
    "24": ("B240", "date-of-coming-into-force", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "25": ("B250／B250EP／B251EP", "language-of-filing", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "26": ("B260", "language-of-publication", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "30": ("B300", "priority-claims", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6；DOCDB手册 PDF p.6–7"),
    "31": ("B310／B310EP／B311EP", "priority-claim/document-id/doc-number", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6"),
    "32": ("B320", "priority-claim/document-id/date", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6"),
    "33": ("B330", "priority-claim/document-id/country", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6"),
    "34": ("B340", "—", "EP全文手册 PDF p.5–9"),
    "40": ("B400", "dates-of-public-availability", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "43": ("B410／B420／B430（未授权公开）", "dates-of-public-availability/unexamined-printed-without-grant", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5"),
    "45": ("B450（授权时出版）", "dates-of-public-availability/examined-printed-with-grant", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6"),
    "46": ("B460（权利要求公开日）", "—", "EP全文手册 PDF p.5–9"),
    "47": ("B470", "—", "EP全文手册 PDF p.5–9"),
    "48": ("B480（更正发布日）", "—", "EP全文手册 PDF p.5–9"),
    "51": ("B510／B510EP", "classification-ipc／classifications-ipcr", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "52": ("B520（EPO 不用）", "classification-national／classification-ecla", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "53": ("B530", "—", "EP全文手册 PDF p.5–9"),
    "54": ("B540（B541 语言/B542 文本）", "invention-title", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "55": ("B550", "—", "EP全文手册 PDF p.5–9（关键词/描述串）"),
    "56": ("B560（B561 专利/B562 非专利/B565EP）", "references-cited/citation", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6；DOCDB手册 PDF p.6–7"),
    "57": ("B570", "abstract", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "58": ("B580", "—", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6"),
    "60": ("B600", "—", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5（us-related-documents）"),
    "61": ("B610", "—", "EP全文手册 PDF p.5–9"),
    "62": ("B620／B620EP", "—", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6（continuation-in-part 等）"),
    "63": ("B630", "—", "EP全文手册 PDF p.5–9"),
    "64": ("B640", "—", "EP全文手册 PDF p.5–9"),
    "65": ("B650", "preceding-publication-date", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "66": ("B660", "—", "EP全文手册 PDF p.5–9"),
    "67": ("B670", "—", "EP全文手册 PDF p.5–9"),
    "68": ("B680（手册未列，SPC 范围外）", "—", "EP全文手册 PDF p.5–9 未列；边界外"),
    "70": ("B700", "parties", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "71": ("B710（B711 名称/地址/iid/irf）", "parties/applicants/applicant", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "72": ("B720（B721）", "parties/inventors/inventor", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5；DOCDB手册 PDF p.6–7"),
    "73": ("B730（B731）", "—", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6（assignees）"),
    "74": ("B740（B741）", "parties/agents", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6；DOCDB手册 PDF p.6–7"),
    "75": ("B710/B720 角色重叠", "—", "EP全文手册 PDF p.5–9（角色重叠不建新元素）"),
    "76": ("B710/B720/B730 角色重叠", "—", "EP全文手册 PDF p.5–9；US授权手册 PDF p.4–6"),
    "81": ("B810", "—", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "83": ("B830", "—", "EP全文手册 PDF p.5–9"),
    "84": ("B840／B844EP（B845EP 扩展国）", "designation-of-states/designation-epc/contracting-states", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "85": ("B850", "—", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5（us-371c12-date）"),
    "86": ("B860（B861 号/日，B862 语言）", "—", "EP全文手册 PDF p.5–9；US申请手册 PDF p.4–5（PCT 数据）"),
    "87": ("B870（B871 号/日）", "—", "EP全文手册 PDF p.5–9"),
    "88": ("B880", "—", "EP全文手册 PDF p.5–9"),
    "91": ("B910", "—", "EP全文手册 PDF p.5–9"),
    "96": ("B860（区域申请）", "application-reference（DOCDB 多格式）", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "97": ("B870（区域公布）", "publication-reference", "EP全文手册 PDF p.5–9；DOCDB手册 PDF p.6–7"),
    "98": ("—（SPC 范围外）", "—", "EP全文手册未列；边界外"),
}


def main():
    out_csv, out_md = sys.argv[1], sys.argv[2]
    header = ['inid', 'meaning_en', 'meaning_cn', 'uspto_xml_path', 'ep_element',
              'docdb_exchange_element', 'official_manual_ref', 'docdb_patstat_ref',
              'entity_attribute', 'note']
    with open(out_csv, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(header)
        for r in ROWS:
            e = EXTRA.get(r[0], ('', '', ''))
            w.writerow([r[0], r[1], r[2], r[3], e[0], e[1], e[2], r[4], r[5], r[6]])
    with open(out_md, 'w', encoding='utf-8') as f:
        f.write('| INID | 含义（英） | 含义（中） | USPTO XML 路径（样例验证） | EP 全文 B 元素 | DOCDB 元素 | 官网手册依据 | DOCDB/PATSTAT 参照 | 本设计实体.属性 | 备注 |\n')
        f.write('|---|---|---|---|---|---|---|---|---|---|\n')
        for r in ROWS:
            e = EXTRA.get(r[0], ('', '', ''))
            cells = [r[0], r[1], r[2], r[3], e[0], e[1], e[2], r[4], r[5], r[6]]
            cells = [str(c).replace('|', '\\|') for c in cells]
            f.write('| (' + cells[0] + ') | ' + ' | '.join(cells[1:]) + ' |\n')
    print(f'wrote {out_csv} ({len(ROWS)} rows), {out_md}')
    missing=[r[0] for r in ROWS if r[0] not in EXTRA]
    print('missing EXTRA:', missing)


if __name__ == '__main__':
    main()
